apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: simple-app-db-creds
  namespace: default
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: simple-app
    meta.helm.sh/release-namespace: default
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: openbao-backend
    kind: SecretStore
  target:
    name: simple-app-secrets
    creationPolicy: Owner
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: "simple-app/db"
        property: host
    - secretKey: DB_PORT
      remoteRef:
        key: "simple-app/db"
        property: port
    - secretKey: DB_NAME
      remoteRef:
        key: "simple-app/db"
        property: database
    - secretKey: DB_USER
      remoteRef:
        key: "simple-app/db"
        property: user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "simple-app/db"
        property: password
