apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eso-openbao
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kirylputseyeu/develop-platform.git
    targetRevision: main
    path: k8s/apps/eso-openbao
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
