apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater
  namespace: argocd
spec:
  project: default
  source:
    chart: argocd-image-updater
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.15.0
    helm:
      values: |
        config:
          applicationsAPIKind: argocd
          registries:
            - name: Docker Hub
              api_url: https://registry-1.docker.io
              prefix: docker.io
              default: true
        metrics:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
