{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "postgresql.name" . }}-credentials
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ .Values.postgresql.passwordSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.postgresql.passwordSecretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: password
    - secretKey: {{ .Values.postgresql.hostSecretKey }}
      remoteRef:
        key: {{ .Values.externalSecrets.remoteRef.key }}
        property: host
{{- end }}
